"""Builds src/lib/mapData.ts from Natural Earth 1:10m admin-0 countries (public domain).
Usage: python3 scripts/build-map.py /path/to/ne_10m_admin_0_countries.geojson
Mercator projection, clipped to the Bay of Bengal / Malacca Strait region."""
import json, math, sys

LON0, LON1, LAT0, LAT1 = 73.0, 104.5, -1.5, 21.0
W = 1600.0
def ym(lat): return math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
K = W / math.radians(LON1 - LON0)
H = (ym(LAT1) - ym(LAT0)) * K
def proj(lon, lat): return ((lon - LON0) / (LON1 - LON0) * W, (ym(LAT1) - ym(lat)) * K)

M = 30
RECT = (-M, -M, W + M, H + M)

def clip(poly):
    def inside(p, e):
        x, y = p
        return [x >= RECT[0], y >= RECT[1], x <= RECT[2], y <= RECT[3]][e]
    def inter(a, b, e):
        (x1, y1), (x2, y2) = a, b
        if e in (0, 2):
            xe = RECT[e]; t = (xe - x1) / (x2 - x1); return (xe, y1 + t * (y2 - y1))
        ye = RECT[e]; t = (ye - y1) / (y2 - y1); return (x1 + t * (x2 - x1), ye)
    out = poly
    for e in range(4):
        if not out: break
        inp, out = out, []
        s = inp[-1]
        for p in inp:
            if inside(p, e):
                if not inside(s, e): out.append(inter(s, p, e))
                out.append(p)
            elif inside(s, e): out.append(inter(s, p, e))
            s = p
    return out

def rdp(pts, eps):
    if len(pts) < 3: return pts
    a, b = pts[0], pts[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]
    n = math.hypot(dx, dy) or 1e-9
    dmax, idx = 0, 0
    for i in range(1, len(pts) - 1):
        d = abs(dy * pts[i][0] - dx * pts[i][1] + b[0] * a[1] - b[1] * a[0]) / n
        if d > dmax: dmax, idx = d, i
    if dmax > eps:
        return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)
    return [a, b]

def area(p):
    return abs(sum(p[i][0] * p[i - 1][1] - p[i - 1][0] * p[i][1] for i in range(len(p)))) / 2

data = json.load(open(sys.argv[1]))
HIGHLIGHT = {"India": "origin", "Malaysia": "destination"}
shapes = []
for f in data["features"]:
    name = f["properties"]["ADMIN"]
    g = f["geometry"]
    polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
    parts = []
    for poly in polys:
        ring = poly[0]
        lons = [c[0] for c in ring]; lats = [c[1] for c in ring]
        if max(lons) < LON0 - 2 or min(lons) > LON1 + 2 or max(lats) < LAT0 - 2 or min(lats) > LAT1 + 2:
            continue
        pts = clip([proj(*c) for c in ring])
        if len(pts) < 3: continue
        half = len(pts) // 2
        pts = rdp(pts[:half + 1], 0.9)[:-1] + rdp(pts[half:] + [pts[0]], 0.9)
        # keep Penang island and other small islands near the route, drop specks elsewhere
        if area(pts) < 6: continue
        parts.append("M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts[:-1]) + "Z")
    if parts:
        shapes.append({"name": name, "role": HIGHLIGHT.get(name, "land"), "d": "".join(parts)})

def point(lon, lat):
    x, y = proj(lon, lat); return {"x": round(x, 1), "y": round(y, 1)}

out = {
    "width": W, "height": round(H, 1),
    "shapes": shapes,
    "points": {
        "chittarkottai": point(78.9000, 9.4289),   # OpenStreetMap / Nominatim
        "georgetown": point(100.3347, 5.4175),     # Lebuh Campbell, OpenStreetMap / Nominatim
        "bayOfBengal": point(88.0, 13.5),
        "andamanSea": point(96.0, 10.5),
        "straitOfMalacca": point(99.6, 3.4),
        "sriLanka": point(80.7, 7.8),
        "tamilNadu": point(78.2, 11.2),
        "sumatra": point(101.0, 0.2),
    },
}
with open(sys.argv[2] if len(sys.argv) > 2 else "src/lib/mapData.ts", "w") as fh:
    fh.write("// Generated by scripts/build-map.py from Natural Earth 1:10m (public domain). Do not edit by hand.\n")
    fh.write("export const mapData = " + json.dumps(out, separators=(",", ":")) + " as const;\n")
print(len(shapes), "shapes", round(H, 1))
